controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\data\ActiveDataProvider;
use app\models\Productos;
use app\models\Proveedores;
use app\models\Telefonos;
use app\models\Reparaciones;
use app\models\Ventas;
use app\models\Rventasproductos;
use app\models\Tickets;
use yii\helpers\Html;
use yii\db\Query;

class SiteController extends Controller {
    
    public function actionEnlace($texto, $enlace) {
        return Html::a($texto, [$enlace]);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['administracion', 'reparaciones', 'carrito', 'crear-carrito'],
                'rules' => [
                    [
                        'actions' => ['administracion'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->isAdmin(Yii::$app->user->identity->cd_ticket);
                        },
                    ],
                    [
                        'actions' => ['reparaciones', 'carrito', 'crear-carrito'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return !Yii::$app->user->isGuest;
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->session->setFlash('loginSuccess', '¡Inicio de sesión exitoso!');
            return $this->goHome();
        } else if ($model->hasErrors()) {
            Yii::$app->session->setFlash('loginError', '¡Algo salio mal! Informanos del error o prueba otra vez.');
        }

        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();
        Yii::$app->session->setFlash('logout', 'Se ha cerrado tu sesión con éxito. ¡Hasta luego!');
        
        return $this->goHome();
    }
    
    public function actionSingin() {
        $model = new Tickets();
        $model->cd_ticket = 'T' . rand(10000, 99999);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->actionLogin();
        }

        return $this->render('singin', [
            'model' => $model,
        ]);
    }

    /**
     * Displays policies page.
     *
     * @return Response|string
     */
    public function actionPoliticas() {
        return $this->render('politicas');
    }

    public function actionAdministracion() {
        $nombres = [
            'Tabla Productos',
            'Tabla Empleados',
            'Tabla Tickets',
            'Tabla Ventas',
            'Tabla Proveedores',
            'Tabla Reparaciones',
            'Tabla Telefonos',
            'Tabla Relación Venta-Producto'
        ];

        $enlaces = [
            'productos/',
            'empleados/',
            'tickets/',
            'ventas/',
            'proveedores/',
            'reparaciones/',
            'telefonos/',
            'rventasproductos/',
        ];
        
        $dataProvider = new ActiveDataProvider([
            'query' => Reparaciones::find()->where(['estado' => null, 'cd_empleado' => null]),
        ]);

        return $this->render('administracion', [
                    'nombres' => $nombres,
                    'enlaces' => $enlaces,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDetalleCatalogo($id) {
        $producto = Productos::findOne($id);
        $proveedor = Proveedores::findOne($producto->cd_proveedor);
        $telefonos = Telefonos::find()->where(['cd_proveedor' => $proveedor->cd_proveedor])->all();
        if (Yii::$app->session->hasFlash('cantidad')) {
            $cantidad = Yii::$app->session->getFlash('cantidad');
        } else {
            $cantidad = null;
        }
        return $this->render('detallecatalogo', ['producto' => $producto,
                    'proveedor' => $proveedor,
                    'telefonos' => $telefonos,
                    'cantidad' => $cantidad,
        ]);
    }

    public function actionCatalogo() {
        $dataProvider = new ActiveDataProvider([
            'query' => Productos::find(),
        ]);
        return $this->render('catalogo', [
                    "dataProvider" => $dataProvider,
        ]);
    }
    
    public function actionAceptarPoliticas() {
        Yii::$app->session->setFlash('politicas', $this->renderPartial('politicas'));
        $cantidad = Yii::$app->request->post('cantidad');
        Yii::$app->session->setFlash('cantidad', $cantidad);
        $id = Yii::$app->request->post('cd_producto');
        return  $this->actionDetalleCatalogo($id);
    }
    
    public function actionReparaciones() {
        $dataProvider = new ActiveDataProvider([
            'query' => Reparaciones::find()
                    ->innerJoinWith('nVenta')
                    ->where(['ventas.cd_ticket' => Yii::$app->user->id])
                    ->andWhere(['IS NOT', 'cd_empleado', null])
                    ->with('cdEmpleado'),
        ]);
        return $this->render('reparaciones', [
                    "dataProvider" => $dataProvider,
        ]);
    }

    public function actionAprobarReparaciones($id) {
        $reparacion = Reparaciones::findOne(['cd_reparacion' => $id]);
        $reparacion->estado = 0;
        $reparacion->save();

        Yii::$app->session->setFlash('aprobarReparacion', 'Su reparación está en la cola y será atendida en breve.');
        return $this->actionReparaciones();
    }
    
    public function actionCancelarReparaciones($id) {
        $reparacion = Reparaciones::findOne($id);
        $reparacion->delete();
        Yii::$app->session->setFlash('cancelarReparacion', 'Lamentamos no continuar con la reparación.');
        return $this->actionReparaciones();
    }
    
    public function actionFormReparaciones($id) {
        $model = null;
        if ($id !== 'newForm') {
            $model = Reparaciones::findOne($id);
        } else {
            $model = new Reparaciones();
            $venta = Ventas::findOne(['cd_ticket' => Yii::$app->user->id]);
            $model->n_venta = $venta->n_venta;
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('crearReparacion', 'Reparación creada con éxito.');
            return $this->actionReparaciones();
        }

        return $this->render('formreparaciones', ['model' => $model]);
    }

    public function actionCarrito() {
        if (!Yii::$app->session->has('carrito')) {
            Yii::$app->session->set('carrito', []);
        }
        $dataProvider = new ActiveDataProvider([
            'query' => Rventasproductos::find()
                    ->with('cdProducto')
                    ->where([
                        'n_venta' =>
                        (new Query())
                        ->select('n_venta')
                        ->from('ventas')
                        ->where(['cd_ticket' => Yii::$app->user->id])
                    ]),
        ]);
        $carrito = Yii::$app->session->get('carrito', []);
        return $this->render('carrito', [
                    "dataProvider" => $dataProvider,
                    "carrito" => $carrito,
        ]);
    }

    public function actionCrearCarrito() {
        $id = Yii::$app->request->post('id');
        $cantidad = Yii::$app->request->post('cantidad');
        $producto = Productos::findOne($id);
        if (!Yii::$app->session->has('carrito')) {
            Yii::$app->session->set('carrito', []);
        }
        $carrito = Yii::$app->session->get('carrito', []);

        $sumarDuplicados = null;
        foreach ($carrito as $indice => $productoCarrito) {
            if ($productoCarrito['id'] == $id) {
                $sumarDuplicados = $indice;
                break;
            }
        }

        if ($sumarDuplicados !== null) {
            $cantidad = intval($cantidad);
            $carrito[$sumarDuplicados]['cantidad'] += $cantidad;
        } else {
            $cantidad = intval($cantidad);
            $carrito[] = [
                'id' => $producto->cd_producto,
                'cantidad' => $cantidad,
                'nombre' => $producto->nombre,
                'precio' => $producto->precio,
            ];
        }
        Yii::$app->session->set('carrito', $carrito);

        Yii::$app->session->setFlash('crearCarrito', 'El producto se ha agregado al carrito.');

views/site/_carrito.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;

?>

<div class="col-md-12 mb-4">
    <div class="card bg-dark text-white">
        <div class="row no-gutters">
            <div class="col-md-1 fix-size">
                <?= Html::a(Html::img("@web/imagenes/producto" . $model->cdProducto->cd_producto . ".jpg", ['class' => 'card-img']), ['site/detalle-catalogo', 'id' => $model->cdProducto->cd_producto]) ?>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <h5 class="card-title"><?= $model->cdProducto->nombre ?></h5>
                    <p class="card-text">Precio: <?= $model->cdProducto->precio ?>€</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card-body">
                    <p class="card-text">Cantidad x<strong><?= $model->cantidad ?></strong></p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <?= Html::a('Solicitar cancelacion', ['site/cancelar-carrito'], ['class' => 'btn btn-primary']) ?>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/_catalogo.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;

?>

<div class="col-md-12 mb-4">
    <div class="card">
        <?= Html::a(Html::img("@web/imagenes/producto" . $model->cd_producto . ".jpg", ['class' => 'card-img-top']), ['site/detalle-catalogo', 'id' => $model->cd_producto]) ?>
        <div class="card-body">
            <h5 class="card-title text-dark"><?= Html::a($model->nombre, ['site/detalle-catalogo', 'id' => $model->cd_producto]) ?></h5>
            <p class="card-text text-dark">Precio: <?= $model->precio ?>€</p>
            <p class="card-text text-dark"><?= $model->descripcion ?></p>
        </div>
        <div class="card-footer">
            <?= Html::a('Ver Detalles', ['site/detalle-catalogo', 'id' => $model->cd_producto], ['class' => 'btn btn-purple']) ?>
        </div>
    </div>
</div>

views/site/_formreparacionesadmin.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\Reparaciones $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="reparaciones-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'diagnostico')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'f_recepcion')->textInput() ?>

    <?= $form->field($model, 'coste')->textInput() ?>

    <?= $form->field($model, 'cd_empleado')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/_formreparacionesclient.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\Reparaciones $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="reparaciones-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'motivo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mot_detalles')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Enviar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/_reparaciones.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;


?>

<div class="col-md-12 mb-4">
    <div class="card bg-dark text-white">
        <div class="row no-gutters">
            <div class="col-md-7">
                <div class="card-body">
                    <h5 class="card-title"><?= $model->motivo ?></h5>
                    <p class="card-text"><strong>Detalles:</strong> <?= $model->mot_detalles ?></p>
                    <p class="card-text"><strong>Diagnóstico:</strong> <?= $model->diagnostico ?></p>
                    <p class="card-text"><strong>Estado:</strong> <?= $model->estado !== null ? ($model->estado ? 'Completado' : 'En proceso') : 'Pendiente' ?></p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card-body">
                    <?php if ($model->cdEmpleado === null): ?>
                        <p class="card-text"><strong>Tecnico:</strong> <?= '' ?> <?= '' ?></p>
                    <?php else: ?>
                        <p class="card-text"><strong>Tecnico:</strong> <?= $model->cdEmpleado->nombre ?> <?= $model->cdEmpleado->apellidos ?></p>
                    <?php endif; ?>
                    <p class="card-text"><strong>Fecha de recogida:</strong> <?= Yii::$app->formatter->asDate($model->f_recepcion, 'php:d/m/Y') ?></p>
                    <p class="card-text"><strong>Coste:</strong> <?= $model->coste ?>€</p>
                </div>
            </div>
            <div class="col-md-2">
                <div class="card-body">
                    <?php if ($model->estado === null): ?>
                        <?= Html::a('Cancelar', ['site/cancelar-reparaciones', 'id' => $model->cd_reparacion], ['class' => 'btn btn-danger']) ?>
                        <p></p>
                        <?= Html::a('Aprobar', ['site/aprobar-reparaciones', 'id' => $model->cd_reparacion], ['class' => 'btn btn-primary']) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/_reparacionesadministracion.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;


?>

<div class="col-md-12 mb-3">
    <div class="card bg-dark text-white">
        <div class="row no-gutters">
            <div class="col-md-3">
                <div class="card-body">
                    <h5 class="card-title"><?= $model->motivo ?></h5>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card-body">
                    <p class="card-text"><strong>Detalles:</strong> <?= $model->mot_detalles ?></p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card-body">
                    <p class="card-text"><strong>Estado:</strong> <?= $model->estado !== null ? ($model->estado ? 'Completado' : 'En proceso') : 'Pendiente' ?></p>
                </div>
            </div>
            <div class="col-md-2">
                <div class="card-body">
                    <?php if ($model->estado === null): ?>
                        <?= Html::a('Presupuestar', ['site/form-reparaciones', 'id' => $model->cd_reparacion], ['class' => 'btn btn-primary']) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/carrito.php
<?php

/** @var yii\web\View $this */
use yii\widgets\ListView;
use yii\helpers\Html;
use yii\bootstrap4\Modal;
use yii\web\View;

$this->title = 'Technonymous';
$title = 'Carrito';
$this->registerJs(
    "
    $(document).ready(function () {
        if (" . (Yii::$app->session->hasFlash('crearCarrito') ? 'true' : 'false') . ") {
            $('#crear-modal').modal('show');
        } else if (" . (Yii::$app->session->hasFlash('guardarCarrito') ? 'true' : 'false') . ") {
            $('#guardar-modal').modal('show');
        } else if (" . (Yii::$app->session->hasFlash('eliminarCarrito') ? 'true' : 'false') . ") {
            $('#eliminar-modal').modal('show');
        } else if (" . (Yii::$app->session->hasFlash('cancelarCarrito') ? 'true' : 'false') . ") {
            $('#cancelar-modal').modal('show');
        }
    });
    ",
    View::POS_READY
);

if (Yii::$app->session->hasFlash('crearCarrito')) {
    Modal::begin([
        'id' => 'crear-modal',
        'title' => 'Añadir al Carrito',
        'footer' => '<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>',
        'headerOptions' => [
            'class' => 'bg-success',]
    ]);
    echo '<p class="text-success">' . Yii::$app->session->getFlash('crearCarrito') . '</p>';
    Modal::end();
} else if (Yii::$app->session->hasFlash('guardarCarrito')) {
    Modal::begin([
        'id' => 'guardar-modal',
        'title' => 'Productos pedidos',
        'footer' => '<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>',
        'headerOptions' => [
            'class' => 'bg-success',]
    ]);
    echo '<p class="text-success">' . Yii::$app->session->getFlash('guardarCarrito') . '</p>';
    Modal::end();
} else if (Yii::$app->session->hasFlash('eliminarCarrito')) {
    Modal::begin([
        'id' => 'eliminar-modal',
        'title' => 'Carrito',
        'footer' => '<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>',
        'headerOptions' => [
            'class' => 'bg-danger',]
    ]);
    echo '<p class="text-danger">' . Yii::$app->session->getFlash('eliminarCarrito') . '</p>';
    Modal::end();
} else if (Yii::$app->session->hasFlash('cancelarCarrito')) {
    Modal::begin([
        'id' => 'cancelar-modal',
        'title' => 'Solicitar cancelacion',
        'footer' => '<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>',
        'headerOptions' => [
            'class' => 'bg-purple',]
    ]);
    echo '<p class="txt-purple">' . Yii::$app->session->getFlash('cancelarCarrito') . '</p>';
    Modal::end();
}
?>
<div>
    <h1><?= $title ?></h1> 
    <?php if (count($carrito) > 0): ?>
        <div class="row">
            <?php foreach ($carrito as $item): ?>
                <div class="col-md-12 mb-4">
                    <div class="card bg-dark text-white">
                        <div class="row no-gutters">
                            <div class="col-md-1 fix-size">
                                <?= Html::a(Html::img("@web/imagenes/producto" . $item['id'] . ".jpg", ['class' => 'card-img']), ['site/detalle-catalogo', 'id' => $item['id']]) ?>
                            </div>
                            <div class="col-md-4">
                                <div class="card-body">
                                    <h5 class="card-title"><?= $item['nombre'] ?></h5>
                                    <p class="card-text">Precio: <?= $item['precio'] ?>€</p>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="card-body">
                                    <p class="card-text">Cantidad x<strong><?= $item['cantidad'] ?></strong></p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="card-body">
                                    <?= Html::a('Eliminar', ['site/eliminar-carrito', 'id' => $item['id']], ['class' => 'btn btn-danger']) ?>
                                    <?= Html::a('Modificar', ['site/modificar-carrito', 'id' => $item['id']], ['class' => 'btn btn-primary']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class="col-md-12 mb-4">
                <?= Html::a('Finalizar Pedido', ['site/guardar-carrito'], ['class' => 'btn btn-success']) ?>
            </div>
        </div>
    <?php else: ?>
        <p>No hay productos en la cesta.</p>
    <?php endif; ?>
    <h2>Pendientes de envio</h2>
    <?php if ($dataProvider->getCount() > 0): ?>
        <div class="row">              
            <?=
            ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_carrito',
                'summary' => false,
                'layout' => "{items}",
            ]);
            ?> 
        </div>
    <?php else: ?>
        <p>No hay productos pedidos.</p>
    <?php endif; ?>
</div>

views/site/catalogo.php
<?php

/** @var yii\web\View $this */
use yii\widgets\ListView;

$this->title = 'Technonymous';
$title = 'Productos';
?>
<div>
    <h1><?= $title ?></h1>   
    <div class="row">              
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_catalogo',
            'summary' => false,
            'layout' => "{items}",
            'options' => ['class' => 'grid'],
        ]); ?> 
    </div>
</div>

views/site/detallecatalogo.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;
use yii\bootstrap4\Modal;
use yii\web\View;
use yii\widgets\ActiveForm;

$this->title = 'Technonymous';
$title = 'Productos';
$this->registerJs(
    "
    $(document).ready(function () {
        $('#politicas-modal').modal('show');
    });
    ",
    View::POS_READY
);
if (Yii::$app->session->hasFlash('politicas')) {
    Modal::begin([
        'id' => 'politicas-modal',
        'title' => 'Políticas',
        'size' => Modal::SIZE_EXTRA_LARGE,
        'headerOptions' => [
            'class' => 'bg-purple',]
    ]);
    echo Yii::$app->session->getFlash('politicas');
    $form = ActiveForm::begin([
        'action' => ['site/crear-carrito'],
        'method' => 'post',
    ]);
    echo Html::hiddenInput('id', $producto->cd_producto);
    echo Html::hiddenInput('cantidad', $cantidad);
    echo Html::submitButton('Añadir al carrito', ['class' => 'btn btn-purple']);
    ActiveForm::end();
    Modal::end();

}
?>

<div>
    <h1><?= $producto->nombre ?></h1>

    <div class="row">
        <div class="col-md-6">
            <div class="imagen-producto">
                <?= Html::img(Yii::getAlias('@web') . "/imagenes/producto" . $producto->cd_producto . ".jpg") ?>
            </div>
        </div>
        <div class="col-md-6 bg-dark rounded p-3">
            <p><strong>Precio: <?= $producto->precio ?>€</strong></p>
            <p>Info: <?= $producto->descripcion ?></p>
            <p><strong>Datos del proveedor: </strong></p>
            <p class="border border-white rounded p-3">
                <strong>Nombre:</strong> <?= $proveedor->nombre ?><br>
                <strong>Teléfono/s:</strong><br>
                <?php foreach ($telefonos as $telefono): ?>
                    <?= $telefono->telefono ?><br>
                <?php endforeach; ?>
                <strong>Dirección:</strong> <?= $proveedor->direccion ?>
            </p>
            <form id="solicitud-form" action="<?= Yii::$app->urlManager->createUrl(['site/aceptar-politicas']) ?>" method="post">
                <input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>">
                <input type="hidden" id="cd_producto" name="cd_producto" value="<?= $producto->cd_producto ?>">
                <div class="form-group d-flex align-items-center">
                    <label for="cantidad" class="mr-2">Cantidad:</label>
                    <div class="col-md-2 input-group flex-grow-1">
                        <input type="number" id="cantidad" name="cantidad" class="form-control input-number" value="1" min="1" max="99">
                    </div>
                </div>
                <?= Html::submitButton('Solicitar Producto', ['class' => 'btn btn-purple', 'id' => 'solicitarBtn']) ?>
            </form>
            <script>
                $(document).ready(function () {
                    $('.btn-number').click(function (e) {
                        e.preventDefault();

                        var fieldName = $(this).attr('data-field');
                        var type = $(this).attr('data-type');
                        var input = $("input[name='" + fieldName + "']");
                        var currentVal = parseInt(input.val());

                        if (!isNaN(currentVal)) {
                            if (type === 'minus') {
                                if (currentVal > input.attr('min')) {
                                    input.val(currentVal - 1).change();
                                }
                            } else if (type === 'plus') {
                                if (currentVal < input.attr('max')) {
                                    input.val(currentVal + 1).change();
                                }
                            }
                        }
                    });

                    $('.input-number').focusin(function () {
                        $(this).data('oldValue', $(this).val());
                    });

                    $('.input-number').change(function () {
                        var minValue = parseInt($(this).attr('min'));
                        var maxValue = parseInt($(this).attr('max'));
                        var valueCurrent = parseInt($(this).val());

                        if (valueCurrent >= minValue) {
                            $(".btn-number[data-type='minus'][data-field='" + $(this).attr('name') + "']").removeAttr('disabled');
                        } else {
                            alert('Sorry, the minimum value was reached');
                            $(this).val($(this).data('oldValue'));
                        }

                        if (valueCurrent <= maxValue) {
                            $(".btn-number[data-type='plus'][data-field='" + $(this).attr('name') + "']").removeAttr('disabled');
                        } else {
                            alert('Sorry, the maximum value was reached');
                            $(this).val($(this).data('oldValue'));
                        }
                    });
                });
            </script>
        </div>
    </div>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/formreparaciones.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Reparaciones $model */

?>
<div class="reparaciones-create bg-dark p-3">
    <?php if ($model->motivo !== null) : ?>
        <h1>Presupuestar Reparacion</h1>
        <?= $this->render('_formreparacionesadmin', ['model' => $model]) ?>
    <?php else : ?>
        <h1>Solicitar Reparacion</h1>
        <?= $this->render('_formreparacionesclient', ['model' => $model]) ?>
    <?php endif; ?>
</div>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Inicio de sesión';
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Rellena los siguientes campos para iniciar sesion:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->label('Usuario')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->label('Contraseña')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ])->label('Recordar')?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-success', 'name' => 'login-button']) ?>
                <?= Html::a('Crear Cuenta', ['site/singin'], ['class' => 'btn btn-primary']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>